# Generated by Django 3.2.13 on 2022-06-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='saleswoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_details',
            field=models.TextField(null=True),
        ),
    ]
