# Generated by Django 3.2.13 on 2022-07-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=25)),
                ('event_venue', models.CharField(max_length=100)),
                ('event_pic', models.ImageField(upload_to='event_pic')),
            ],
        ),
    ]
